### ISSUE TITLE
看看腿

### ISSUE THREAD

**Issue by xiaoqi433** [KarinJS/Karin#142]

**Comment by yusheng929** [comment]
@shijinn520 看看腿

**Comment by shijinn520** [comment]
干什么！

**Comment by yusheng929** [comment]
> 干什么！
> 

那就舔舔腿

**Comment by yusheng929** [comment]
> 干什么！
> 

![Image_1723827507849.jpg](https://github.com/user-attachments/assets/6be9c8c0-3c93-43a8-acde-fa087d07f7e2)
