### ISSUE TITLE
Api请求错误 发送超时

### ISSUE THREAD

**Issue by lingdu2333** [KarinJS/Karin#15]
![image](https://github.com/KarinJS/Karin/assets/117048039/8968b872-2a9f-4869-8cac-5f7c9bffe3d6)
当BOT出现群消息过多时 回复消息时会报错”发送超时“（但消息似乎正常发送了）
测试环境为 Karin 0.0.2 LLOneBOT 3.26.6 QQ9.9.11

**Comment by CalmLexi** [comment]
这个是LLOneBOT返回的数据，如果说发送成功了，那就是llob那边判断有问题了

**Comment by CalmLexi** [comment]
请提供一下发送的数据
打开debug
