### ISSUE TITLE
Feat: 事件监听器

### ISSUE THREAD

**Issue by Aliorpse** [KarinJS/Karin#176]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 最新版本的`Karin`
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 `Karin` 相关的，且可以实现.

## 描述功能

为karin内部一些事件开放一个监听器函数
比如说开始处理指令，结束处理指令，开关机等

## 动机

因为我不会自己监听（
想开发一个消息处理插件，当一个群聊内有多个机器人时一次指令只会使一个机器人回复
“有消息触发指令的时候将该消息填入队列，如果接收到其他消息与队列中的消息重合则不做处理，指令执行完成后清除消息”

## 实现方法

请提供您认为可以实现此功能的方法，如果您不知道如何实现，可以留空。  
当然，如果您有兴趣，也可以自己实现并向我们提交 Pull Request。

## 功能描述

简要描述你希望增加的功能。

## 替代方案

是否有其他可行的替代方案？

## 附加信息

任何额外的上下文或截图。

**Comment by shijinn520** [comment]
如果仅仅是为了满足多个触发 更建议使用`群cd`功能。

另外，至于开关机，关机你可以自己监听程序结束事件，开机你自己写一个插件 被触发就代表着是开机。

**Comment by shijinn520** [comment]
karin函数本身就是一个监听器。

```js
import karin from 'node-karin'

karin.on(...)
karin.emit(...)

```

![image](https://github.com/user-attachments/assets/f79c26ef-2be1-4b60-897c-7b4b0d865ba9)

**Comment by Aliorpse** [comment]
> karin函数本身就是一个监听器。
> 
> ```js
> import karin from 'node-karin'
> 
> karin.on(...)
> karin.emit(...)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/74231782/367583987-f79c26ef-2be1-4b60-897c-7b4b0d865ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDY1MDAsIm5iZiI6MTcyNjQwNjIwMCwicGF0aCI6Ii83NDIzMTc4Mi8zNjc1ODM5ODctZjc5YzI2ZWYtMmJlMS00YjYwLTg5N2MtN2I0YjBkODY1YmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzMTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZGMxZTcyZjk1Nzc0OWMxNjIyMWVlNjhjYzQxOGJiN2Q0NzFmNjZmOTE5M2MyYmIxYmUzZjI2ZmQ0NzZkMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JMx-UjDOQHf9gifeQzj2OJ78nthlQPckOrXxY58EaMI)

好的，感谢
