### ISSUE TITLE
Bug: 当有其他的export导出时，无法通过class导出

### ISSUE THREAD

**Issue by lava081** [KarinJS/Karin#190]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是最新版本的`Karin`
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

## 描述问题

在example目录中的js如果使用class导出，并且有其他的export供其他js调用，会造成该js的class不被加载

## 复现步骤

详细描述如何复现该问题：

1.在example目录中创建js
2.export class CommandRunner extends plugin {
...
}
export async function Cmd () {
...
}

## 预期行为

按PluginRule中的条件响应正则

## 实际行为

只加载js，不响应正则

## 环境信息

- 操作系统：Ubuntu 24.04 LTS
- Node.js 版本：20.18.0
- 项目版本：0.12.20

## 附加信息

任何额外的上下文或截图。

**Comment by shijinn520** [comment]
已知问题 等待新版本发版修复
