### ISSUE TITLE
Feat: 前台重启，像trss-yunzai

### ISSUE THREAD

**Issue by Aliorpse** [KarinJS/Karin#196]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 最新版本的`Karin`
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 `Karin` 相关的，且可以实现.

## 描述功能

如题

## 动机

麻烦

## 实现方法

请提供您认为可以实现此功能的方法，如果您不知道如何实现，可以留空。  
当然，如果您有兴趣，也可以自己实现并向我们提交 Pull Request。

## 功能描述

简要描述你希望增加的功能。

## 替代方案

是否有其他可行的替代方案？

## 附加信息

任何额外的上下文或截图。

**Comment by shijinn520** [comment]
一直都支持

**Comment by Aliorpse** [comment]
> 一直都支持

现在的karin不是重启开启一个黑窗口吗...
![image](https://github.com/user-attachments/assets/b425b7ae-a7f8-4636-8af6-3aab7892ad52)

**Comment by shijinn520** [comment]
> > 一直都支持
> 
> 现在的karin不是重启开启一个黑窗口吗...
> ![image](https://github.com/user-attachments/assets/b425b7ae-a7f8-4636-8af6-3aab7892ad52)
> 

你这是后台启动 npx karin查看全部指令

**Comment by shijinn520** [comment]
> > > > 一直都支持
> > > 
> > > 
> > > 现在的karin不是重启开启一个黑窗口吗...
> > > ![image](https://private-user-images.githubusercontent.com/98144240/389180410-b425b7ae-a7f8-4636-8af6-3aab7892ad52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNDcyMDQsIm5iZiI6MTczMjM0NjkwNCwicGF0aCI6Ii85ODE0NDI0MC8zODkxODA0MTAtYjQyNWI3YWUtYTdmOC00NjM2LThhZjYtM2FhYjc4OTJhZDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDA3MjgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYmFjZjY4YTZjNmVhYmNmNzEyNmQ1YTMzZjc3MjE0MWNiYmY5MmRiYTUwNmQyNWFiZTg0MWYwOTZiZWU0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IxJgpWR2zXgCku1CtsC5siD45rfNBfwHPE8bI4GBSVY)
> > 
> > 
> > 你这是后台启动 npx karin查看全部指令
> 
> 我指的是希望`#重启`时默认前台启动,而不是执行后台启动

插件那边有配置 你自己看配置文件 可以改
