### ISSUE TITLE
Bug: vue渲染

### ISSUE THREAD

**Issue by shijinn520** [KarinJS/Karin#56]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是最新版本的`Karin`
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

## 描述问题

简要描述遇到的问题。

## 复现步骤

详细描述如何复现该问题：

1. 第一步
2. 第二步
3. ...

## 预期行为

预期应该发生什么？

## 实际行为

实际发生了什么？

## 环境信息

- 操作系统：
- Node.js 版本：
- 项目版本：

## 附加信息

任何额外的上下文或截图。

**Comment by shijinn520** [comment]
t

**Comment by ChisatoNishikigi73** [comment]
这是甚么

**Comment by shijinn520** [comment]
> 这是甚么

鸽子项

**Comment by ChisatoNishikigi73** [comment]
> > 这是甚么
> 
> 
> 
> 鸽子项

是不是可以build：vue

**Comment by shijinn520** [comment]
> > > 这是甚么
> > 
> > 
> > 鸽子项
> 
> 是不是可以build：vue

渲染和本体是拆开的。vue那些依赖太大了。

**Comment by shijinn520** [comment]
![image](https://github.com/user-attachments/assets/e1c0a681-a48f-4b0e-9bd6-67dea25f07d1)
![image](https://github.com/user-attachments/assets/6f4075f3-8ce6-431a-9f08-5fe238e2b226)


> > > > > 这是甚么
> > > > 
> > > > 
> > > > 鸽子项
> > > 
> > > 
> > > 是不是可以build：vue
> > 
> > 
> > 渲染和本体是拆开的。vue那些依赖太大了。
> 
> <img alt="image" width="858" src="https://private-user-images.githubusercontent.com/89033115/367588345-8318c8c2-455b-4b71-933c-78b9f6f4be21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTY4NzIsIm5iZiI6MTcyNjQxNjU3MiwicGF0aCI6Ii84OTAzMzExNS8zNjc1ODgzNDUtODMxOGM4YzItNDU1Yi00YjcxLTkzM2MtNzhiOWY2ZjRiZTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE2MDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMDQ1N2I4ZWZkNjU5MGFiN2E4YTI1NDlmMzI0YWU2YjBmZjAwY2VjYWY0MjY4NzY2MzcxNDcyYTI5MmY2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xargKpTdh4NkQByU_4qkee_mSJtcZWVkjADBK_ZfTfY"> 我去算了，eleplus+vue一堆+webpack只需要10mb，我觉得这个可以实现🧐

**Comment by ChisatoNishikigi73** [comment]
> ![image](https://private-user-images.githubusercontent.com/74231782/367596530-e1c0a681-a48f-4b0e-9bd6-67dea25f07d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTcwOTYsIm5iZiI6MTcyNjQxNjc5NiwicGF0aCI6Ii83NDIzMTc4Mi8zNjc1OTY1MzAtZTFjMGE2ODEtYTQ4Zi00YjBlLTliZDYtNjdkZWEyNWYwN2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE2MTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNmJjYTJjYjA2MTJiMGZkMGJjNWI5MTExZWI4MGFjNjNkYjAxNDZkNTlhYjFhMmIzODE0ZDgzZjFjNmZlYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k6dNuKx75WvP18Gm4jK8H9Acz3ARpTAMEKfjAXAOU6U) ![image](https://private-user-images.githubusercontent.com/74231782/367596551-6f4075f3-8ce6-431a-9f08-5fe238e2b226.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTcwOTYsIm5iZiI6MTcyNjQxNjc5NiwicGF0aCI6Ii83NDIzMTc4Mi8zNjc1OTY1NTEtNmY0MDc1ZjMtOGNlNi00MzFhLTlmMDgtNWZlMjM4ZTJiMjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE2MTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MzFmNTEyOGViMTZhN2FlMjE5MmE5NzQzZTUyOTU2ODc0Nzg0YzA5ZGZlN2JhY2M1NDVlNzEzZjNjZWNlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XXJoHjFq6-aTPm2qI2A7csJjAXWxYMFnqZ-feDggMxo)
> 
> > > > > > 这是甚么
> > > > > 
> > > > > 
> > > > > 鸽子项
> > > > 
> > > > 
> > > > 是不是可以build：vue
> > > 
> > > 
> > > 渲染和本体是拆开的。vue那些依赖太大了。
> > 
> > 
> > <img alt="image" width="858" src="https://private-user-images.githubusercontent.com/89033115/367588345-8318c8c2-455b-4b71-933c-78b9f6f4be21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTY4NzIsIm5iZiI6MTcyNjQxNjU3MiwicGF0aCI6Ii84OTAzMzExNS8zNjc1ODgzNDUtODMxOGM4YzItNDU1Yi00YjcxLTkzM2MtNzhiOWY2ZjRiZTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE2MDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMDQ1N2I4ZWZkNjU5MGFiN2E4YTI1NDlmMzI0YWU2YjBmZjAwY2VjYWY0MjY4NzY2MzcxNDcyYTI5MmY2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xargKpTdh4NkQByU_4qkee_mSJtcZWVkjADBK_ZfTfY"> 我去算了，eleplus+vue一堆+webpack只需要10mb，我觉得这个可以实现🧐

20mb我觉得也不错诶
