### ISSUE TITLE
使用onebota链接karin会出现频道号为4的问题

### ISSUE THREAD

**Issue by rainbowwarmth** [KarinJS/Karin#6]
![image](https://github.com/KarinJS/Karin/assets/94736026/e9f23ac1-1085-4844-bc0c-cb81f29a9548)

**Comment by Loli-Lain** [comment]
对于qqbot 需要特殊处理 可以稍等我这几天忙完把适配器写出来 onebots这边我会跟凉菜佬反馈下。

**Comment by Loli-Lain** [comment]
[karin-adapter-QQBot-SDK](https://github.com/KarinJS/karin-adapter-QQBot-SDK)
最后请问一下，是需要接入频道吗？

**Comment by rainbowwarmth** [comment]
对的 @Loli-Lain
